export const languageOptions = [
  { code: "en", short: "EN", label: "English", htmlLang: "en" },
  { code: "fr", short: "FR", label: "Français (Québec)", htmlLang: "fr-CA" },
  { code: "pt", short: "PT", label: "Português", htmlLang: "pt-BR" },
  { code: "it", short: "IT", label: "Italiano", htmlLang: "it" },
  { code: "de", short: "DE-CH", label: "Deutsch (Schweiz)", htmlLang: "de-CH" }
];

const contactDetails = {
  email: "brunoeliassantos097@gmail.com",
  whatsapp: "+55 47 99268-3132"
};

const tech = {
  build: ["HTML", "CSS", "JavaScript", "React", "Next.js", "Tailwind CSS", "Front-End", "Back-End", "Web Apps"],
  connect: ["REST APIs", "Webhooks", "Meta API", "WhatsApp API", "Payment Integrations", "Klumify", "Marketing Infrastructure"],
  automate: ["n8n", "Make", "CRM", "Workflow Automation", "Lead Routing", "AI Prospecting"],
  think: ["AI Agents", "LLMs", "Lead Qualification", "Tool Calling", "AI Prospecting", "Customer Service"],
  data: ["PostgreSQL", "Supabase", "Data Architecture", "Dashboards", "Business Logic", "Klumify"],
  ship: ["Vercel", "Railway", "GitHub", "Docker", "VPS", "Production Workflows"]
};

const dictionaries = {
  en: {
    nav: ["About", "Work", "Experience", "Journey", "Stack", "Contact"], contact: "Contact", selectLanguage: "Select language",
    hero: { role: "AI · Automation · Software · Business Systems", headline: "I build systems around real business problems.", manifesto: "Built through curiosity, practice and iteration.", subheadline: "AI, automation, CRM, APIs, software products, payment infrastructure and digital operations.", badges: ["Based in Brazil", "Open to Québec", "Currently learning French"], ageSuffix: " years old", work: "Explore my work", about: "About me" },
    about: { eyebrow: "Who is Bruno?", title: "A builder shaped by real operations.", strap: "Built through practice, not a perfect roadmap", facts: [["Perspective", "Business + Technology"], ["Method", "Build · Break · Learn"], ["Direction", "Products & Systems"]], paragraphs: ["I’m not someone who learned technology by following a perfect roadmap. My background started around marketing, sales and digital businesses. Working close to real operations made me curious about what was happening behind the tools we used.", "That curiosity gradually took me deeper into technology: automation, APIs, databases, AI, CRM systems, front-end, back-end and product development.", "Most of what I know came from building things, breaking things, solving problems and learning what was necessary to make the next idea work. Practice has always been at the center of my development.", "I’m naturally reserved. I prefer understanding the problem, building something useful and seeing it work.", "I’m skeptical of shortcuts. Real competence takes time. I still have a lot to learn — and that is exactly what keeps me building."], highlights: ["Business perspective", "Product thinking", "Technical execution", "Reserved by nature", "Always learning"], location: "Currently based in Brazil. Open to international opportunities and particularly interested in building my next professional chapter in Québec. Currently studying French." },
    services: { eyebrow: "Capabilities", title: "What I can build and connect.", subtitle: "Technology is useful when its layers work together. These are the areas I combine to ship complete systems.", items: [["Build", "Front-end, back-end, web applications and product interfaces."], ["Connect", "APIs, webhooks, Meta, WhatsApp and third-party platforms."], ["Automate", "n8n, CRM systems, workflows and operational business logic."], ["Think", "AI agents, qualification systems, LLM workflows and decision layers."], ["Data", "PostgreSQL, Supabase, dashboards and practical data architecture."], ["Ship", "Vercel, Railway, GitHub, VPS, Docker and production delivery."]], stats: ["Technical layers", "Product mindset", "Room to learn"] },
    technology: { eyebrow: "Technology in context", title: "Tools connected to outcomes.", subtitle: "A toolkit refined for craft — not for show.", groups: ["Build", "Connect", "Automate", "Think", "Data", "Ship"], toolsLabel: "tools", full: "Full toolkit" },
    learning: { eyebrow: "How I learn", title: "Skills that accumulated.", text: "I didn’t replace business skills with technology. Each layer changed how I understand and build the next one.", steps: ["Marketing", "Sales", "Digital products", "Paid traffic", "Automation", "CRM", "APIs", "Development", "Databases", "Artificial intelligence", "Complete products"] },
    contactSection: { eyebrow: "Contact", title: "Let’s build something that deserves to exist.", text: "I’m open to product, software, automation and AI opportunities where business context matters as much as technical execution.", email: "E-mail", whatsapp: "WhatsApp", sendWhatsapp: "Send WhatsApp message", sendEmail: "Send e-mail", signature: "— Bruno", footer: "Built with curiosity, end-to-end." },
    misc: { scroll: "scroll", age: "years old", discovery: "Discover" }
  },
  fr: {
    nav: ["Profil", "Projets", "Expérience", "Parcours", "Technologies", "Contact"], contact: "Contact", selectLanguage: "Choisir la langue",
    hero: { role: "IA · Logiciel · Automatisation · Systèmes numériques", headline: "Je conçois des technologies autour de vrais enjeux d’affaires.", manifesto: "Construit avec curiosité, pratique et beaucoup d’essais-erreurs.", subheadline: "Systèmes d’IA, automatisation d’entreprise, CRM, API, infrastructure de paiement, applications web et produits numériques.", badges: ["Basé au Brésil", "Ouvert à l’international", "J’apprends le français"], ageSuffix: " ans", work: "Explorer mes projets →", about: "À propos" },
    about: { eyebrow: "Qui est Bruno?", title: "Un bâtisseur formé par les opérations réelles.", strap: "Apprendre par la pratique, sans parcours tout tracé", facts: [["Perspective", "Affaires + Technologie"], ["Méthode", "Construire · Tester · Apprendre"], ["Direction", "Produits et systèmes"]], paragraphs: ["Je n’ai pas appris la technologie en suivant un parcours parfait. J’ai commencé dans le marketing, la vente et les entreprises numériques. Travailler près des opérations m’a donné envie de comprendre ce qui se passait derrière les outils.", "Cette curiosité m’a mené vers l’automatisation, les API, les bases de données, l’IA, les CRM, le front-end, le back-end et le développement de produits.", "J’ai surtout appris en construisant, en brisant, en résolvant des problèmes et en étudiant ce qu’il fallait pour réaliser l’idée suivante. La pratique a toujours été au cœur de mon développement.", "Je suis naturellement réservé. Je préfère comprendre le problème, bâtir quelque chose d’utile et le voir fonctionner.", "Je me méfie des raccourcis. La compétence réelle demande du temps. Il me reste beaucoup à apprendre — et c’est précisément ce qui me pousse à continuer."], highlights: ["Vision d’affaires", "Pensée produit", "Exécution technique", "Nature réservée", "Toujours en apprentissage"], location: "Je vis actuellement au Brésil. Je suis ouvert aux occasions internationales et particulièrement intéressé à bâtir mon prochain chapitre professionnel au Québec. J’étudie présentement le français." },
    services: { eyebrow: "Compétences", title: "Ce que je peux bâtir et connecter.", subtitle: "La technologie devient utile lorsque ses différentes couches fonctionnent ensemble. Je les combine pour livrer des systèmes complets.", items: [["Bâtir", "Front-end, back-end, applications web et interfaces produit."], ["Connecter", "API, webhooks, Meta, WhatsApp et plateformes externes."], ["Automatiser", "n8n, CRM, flux de travail et logique opérationnelle."], ["Réfléchir", "Agents d’IA, qualification, flux LLM et couches décisionnelles."], ["Données", "PostgreSQL, Supabase, tableaux de bord et architecture de données."], ["Déployer", "Vercel, Railway, GitHub, VPS, Docker et mise en production."]], stats: ["Couches techniques", "Pensée produit", "Toujours apprendre"] },
    technology: { eyebrow: "Technologie en contexte", title: "Des outils reliés aux résultats.", subtitle: "Une boîte à outils affinée par la pratique, pas pour la vitrine.", groups: ["Bâtir", "Connecter", "Automatiser", "Réfléchir", "Données", "Déployer"], toolsLabel: "outils", full: "Boîte à outils complète" },
    learning: { eyebrow: "Comment j’apprends", title: "Des compétences qui s’accumulent.", text: "Je n’ai pas remplacé mes compétences d’affaires par la technologie. Chaque couche transforme ma façon de comprendre et de construire la suivante.", steps: ["Marketing", "Vente", "Produits numériques", "Publicité numérique", "Automatisation", "CRM", "API", "Développement", "Bases de données", "Intelligence artificielle", "Produits complets"] },
    contactSection: { eyebrow: "Contact", title: "Bâtissons quelque chose qui mérite d’exister.", text: "Je suis ouvert aux occasions en produit, logiciel, automatisation et IA où le contexte d’affaires compte autant que l’exécution technique.", email: "Courriel", whatsapp: "WhatsApp", sendWhatsapp: "Écrire sur WhatsApp", sendEmail: "Envoyer un courriel", signature: "— Bruno", footer: "Construit avec curiosité, de bout en bout." },
    misc: { scroll: "défiler", age: "ans", discovery: "Découvrir" }
  },
  pt: {
    nav: ["Sobre", "Projetos", "Experiência", "Jornada", "Tecnologias", "Contato"], contact: "Contato", selectLanguage: "Selecionar idioma",
    hero: { role: "IA · Software · Automação · Sistemas Digitais", headline: "Eu construo tecnologia para problemas reais de negócio.", manifesto: "Construído com curiosidade, prática e muita tentativa e erro.", subheadline: "Sistemas de IA, automação empresarial, CRM, APIs, infraestrutura de pagamentos, aplicações web e produtos digitais.", badges: ["Baseado no Brasil", "Aberto ao mundo", "Estudando francês"], ageSuffix: " anos", work: "Explorar meus projetos →", about: "Sobre mim" },
    about: { eyebrow: "Quem é Bruno?", title: "Um construtor formado por operações reais.", strap: "Aprendizado pela prática, sem um roteiro perfeito", facts: [["Perspectiva", "Negócios + Tecnologia"], ["Método", "Construir · Quebrar · Aprender"], ["Direção", "Produtos e sistemas"]], paragraphs: ["Não sou alguém que aprendeu tecnologia seguindo um roteiro perfeito. Minha história começou no marketing, em vendas e negócios digitais. Trabalhar perto de operações reais despertou minha curiosidade sobre o que existia por trás das ferramentas.", "Essa curiosidade me levou para automação, APIs, bancos de dados, IA, CRM, front-end, back-end e desenvolvimento de produtos.", "Aprendi principalmente construindo, quebrando, resolvendo problemas e estudando o necessário para fazer a próxima ideia funcionar. A prática sempre esteve no centro do meu desenvolvimento.", "Sou naturalmente reservado. Prefiro entender o problema, construir algo útil e ver aquilo funcionando.", "Desconfio de atalhos. Competência real leva tempo. Ainda tenho muito a aprender — e é exatamente isso que me mantém construindo."], highlights: ["Visão de negócios", "Pensamento de produto", "Execução técnica", "Reservado por natureza", "Sempre aprendendo"], location: "Atualmente moro no Brasil. Estou aberto a oportunidades internacionais e especialmente interessado em construir meu próximo capítulo profissional no Québec. Atualmente estudo francês." },
    services: { eyebrow: "Capacidades", title: "O que posso construir e conectar.", subtitle: "A tecnologia é útil quando suas camadas trabalham juntas. Combino essas áreas para entregar sistemas completos.", items: [["Construir", "Front-end, back-end, aplicações web e interfaces de produto."], ["Conectar", "APIs, webhooks, Meta, WhatsApp e plataformas externas."], ["Automatizar", "n8n, CRM, fluxos e lógica operacional de negócios."], ["Pensar", "Agentes de IA, qualificação, fluxos com LLMs e decisões."], ["Dados", "PostgreSQL, Supabase, dashboards e arquitetura de dados."], ["Publicar", "Vercel, Railway, GitHub, VPS, Docker e produção."]], stats: ["Camadas técnicas", "Mentalidade de produto", "Espaço para aprender"] },
    technology: { eyebrow: "Tecnologia em contexto", title: "Ferramentas conectadas a resultados.", subtitle: "Um conjunto refinado pela prática — não para decoração.", groups: ["Construir", "Conectar", "Automatizar", "Pensar", "Dados", "Publicar"], toolsLabel: "ferramentas", full: "Todas as ferramentas" },
    learning: { eyebrow: "Como eu aprendo", title: "Habilidades que se acumularam.", text: "Não troquei minhas habilidades de negócios por tecnologia. Cada camada mudou a maneira como entendo e construo a próxima.", steps: ["Marketing", "Vendas", "Produtos digitais", "Tráfego pago", "Automação", "CRM", "APIs", "Desenvolvimento", "Bancos de dados", "Inteligência artificial", "Produtos completos"] },
    contactSection: { eyebrow: "Contato", title: "Vamos construir algo que mereça existir.", text: "Estou aberto a oportunidades em produto, software, automação e IA em que o contexto de negócio importe tanto quanto a execução técnica.", email: "E-mail", whatsapp: "WhatsApp", sendWhatsapp: "Enviar mensagem no WhatsApp", sendEmail: "Enviar e-mail", signature: "— Bruno", footer: "Construído com curiosidade, de ponta a ponta." },
    misc: { scroll: "role", age: "anos", discovery: "Descobrir" }
  },
  it: {
    nav: ["Profilo", "Progetti", "Esperienza", "Percorso", "Tecnologie", "Contatti"], contact: "Contatti", selectLanguage: "Seleziona lingua",
    hero: { role: "IA · Software · Automazione · Sistemi digitali", headline: "Costruisco tecnologia attorno a problemi aziendali reali.", manifesto: "Costruito con curiosità, pratica e molti tentativi ed errori.", subheadline: "Sistemi di IA, automazione aziendale, CRM, API, infrastrutture di pagamento, applicazioni web e prodotti digitali.", badges: ["Con base in Brasile", "Aperto a opportunità internazionali", "Studio il francese"], ageSuffix: " anni", work: "Esplora i miei progetti →", about: "Chi sono" },
    about: { eyebrow: "Chi è Bruno?", title: "Un costruttore formato dalle operazioni reali.", strap: "Imparare con la pratica, senza una strada perfetta", facts: [["Prospettiva", "Business + Tecnologia"], ["Metodo", "Costruire · Rompere · Imparare"], ["Direzione", "Prodotti e sistemi"]], paragraphs: ["Non ho imparato la tecnologia seguendo un percorso perfetto. Ho iniziato nel marketing, nelle vendite e nelle imprese digitali. Lavorare vicino alle operazioni reali mi ha reso curioso di capire cosa ci fosse dietro gli strumenti.", "Questa curiosità mi ha portato verso automazione, API, database, IA, CRM, front-end, back-end e sviluppo di prodotti.", "Ho imparato soprattutto costruendo, rompendo, risolvendo problemi e studiando ciò che serviva per realizzare l’idea successiva. La pratica è sempre stata al centro del mio sviluppo.", "Sono riservato per natura. Preferisco capire il problema, costruire qualcosa di utile e vederlo funzionare.", "Non credo nelle scorciatoie. La vera competenza richiede tempo. Ho ancora molto da imparare — ed è proprio questo che mi spinge a continuare."], highlights: ["Visione aziendale", "Pensiero di prodotto", "Esecuzione tecnica", "Riservato per natura", "Sempre in apprendimento"], location: "Attualmente vivo in Brasile. Sono aperto a opportunità internazionali e particolarmente interessato a costruire il mio prossimo capitolo professionale in Québec. Sto studiando il francese." },
    services: { eyebrow: "Competenze", title: "Ciò che posso costruire e collegare.", subtitle: "La tecnologia è utile quando i suoi livelli lavorano insieme. Combino queste aree per realizzare sistemi completi.", items: [["Costruire", "Front-end, back-end, applicazioni web e interfacce di prodotto."], ["Collegare", "API, webhook, Meta, WhatsApp e piattaforme esterne."], ["Automatizzare", "n8n, CRM, flussi di lavoro e logica operativa."], ["Pensare", "Agenti IA, qualificazione, flussi LLM e livelli decisionali."], ["Dati", "PostgreSQL, Supabase, dashboard e architettura dei dati."], ["Distribuire", "Vercel, Railway, GitHub, VPS, Docker e produzione."]], stats: ["Livelli tecnici", "Mentalità di prodotto", "Spazio per imparare"] },
    technology: { eyebrow: "Tecnologia nel contesto", title: "Strumenti collegati ai risultati.", subtitle: "Una dotazione affinata con la pratica, non per apparire.", groups: ["Costruire", "Collegare", "Automatizzare", "Pensare", "Dati", "Distribuire"], toolsLabel: "strumenti", full: "Dotazione completa" },
    learning: { eyebrow: "Come imparo", title: "Competenze che si accumulano.", text: "Non ho sostituito le competenze aziendali con la tecnologia. Ogni livello ha cambiato il modo in cui comprendo e costruisco il successivo.", steps: ["Marketing", "Vendite", "Prodotti digitali", "Pubblicità a pagamento", "Automazione", "CRM", "API", "Sviluppo", "Database", "Intelligenza artificiale", "Prodotti completi"] },
    contactSection: { eyebrow: "Contatti", title: "Costruiamo qualcosa che meriti di esistere.", text: "Sono aperto a opportunità in prodotto, software, automazione e IA dove il contesto aziendale conta quanto l’esecuzione tecnica.", email: "E-mail", whatsapp: "WhatsApp", sendWhatsapp: "Scrivimi su WhatsApp", sendEmail: "Invia un’e-mail", signature: "— Bruno", footer: "Costruito con curiosità, dall’inizio alla fine." },
    misc: { scroll: "scorri", age: "anni", discovery: "Scopri" }
  },
  de: {
    nav: ["Profil", "Projekte", "Erfahrung", "Werdegang", "Technologien", "Kontakt"], contact: "Kontakt", selectLanguage: "Sprache wählen",
    hero: { role: "KI · Software · Automation · Digitale Systeme", headline: "Ich entwickle Technologie für reale Geschäftsprobleme.", manifesto: "Entstanden aus Neugier, Praxis und vielen Versuchen.", subheadline: "KI-Systeme, Geschäftsautomation, CRM, APIs, Zahlungsinfrastruktur, Webanwendungen und digitale Produkte.", badges: ["In Brasilien ansässig", "Offen für internationale Chancen", "Ich lerne Französisch"], ageSuffix: " Jahre alt", work: "Meine Projekte entdecken →", about: "Über mich" },
    about: { eyebrow: "Wer ist Bruno?", title: "Ein Entwickler, geprägt von realen Abläufen.", strap: "Durch Praxis gelernt, ohne perfekten Fahrplan", facts: [["Perspektive", "Business + Technologie"], ["Methode", "Bauen · Testen · Lernen"], ["Richtung", "Produkte und Systeme"]], paragraphs: ["Ich habe Technologie nicht nach einem perfekten Fahrplan gelernt. Mein Weg begann im Marketing, im Verkauf und in digitalen Unternehmen. Die Nähe zu realen Abläufen weckte meine Neugier auf das, was hinter den eingesetzten Werkzeugen passiert.", "Diese Neugier führte mich tiefer in Automation, APIs, Datenbanken, KI, CRM-Systeme, Front-End, Back-End und Produktentwicklung.", "Am meisten lernte ich, indem ich Dinge baute, Fehler machte, Probleme löste und mir das Wissen für die nächste Idee aneignete. Praxis stand immer im Zentrum meiner Entwicklung.", "Ich bin von Natur aus zurückhaltend. Lieber verstehe ich das Problem, entwickle etwas Nützliches und sehe, wie es funktioniert.", "Ich glaube nicht an Abkürzungen. Echte Kompetenz braucht Zeit. Ich habe noch viel zu lernen — und genau das hält mich am Bauen."], highlights: ["Geschäftsverständnis", "Produktdenken", "Technische Umsetzung", "Von Natur aus zurückhaltend", "Immer am Lernen"], location: "Ich lebe derzeit in Brasilien. Ich bin offen für internationale Möglichkeiten und besonders daran interessiert, mein nächstes berufliches Kapitel in Québec aufzubauen. Zurzeit lerne ich Französisch." },
    services: { eyebrow: "Kompetenzen", title: "Was ich entwickeln und verbinden kann.", subtitle: "Technologie schafft Wert, wenn ihre Ebenen zusammenspielen. Ich verbinde diese Bereiche zu vollständigen Systemen.", items: [["Entwickeln", "Front-End, Back-End, Webanwendungen und Produktoberflächen."], ["Verbinden", "APIs, Webhooks, Meta, WhatsApp und externe Plattformen."], ["Automatisieren", "n8n, CRM, Workflows und operative Geschäftslogik."], ["Denken", "KI-Agenten, Qualifizierung, LLM-Workflows und Entscheidungslogik."], ["Daten", "PostgreSQL, Supabase, Dashboards und Datenarchitektur."], ["Ausliefern", "Vercel, Railway, GitHub, VPS, Docker und Produktivbetrieb."]], stats: ["Technische Ebenen", "Produktdenken", "Raum zum Lernen"] },
    technology: { eyebrow: "Technologie im Kontext", title: "Werkzeuge mit Bezug zum Ergebnis.", subtitle: "Ein Werkzeugkasten, geschärft durch Praxis — nicht für die Show.", groups: ["Entwickeln", "Verbinden", "Automatisieren", "Denken", "Daten", "Ausliefern"], toolsLabel: "Werkzeuge", full: "Vollständiger Werkzeugkasten" },
    learning: { eyebrow: "Wie ich lerne", title: "Fähigkeiten, die aufeinander aufbauen.", text: "Ich habe Geschäftswissen nicht durch Technologie ersetzt. Jede Ebene verändert, wie ich die nächste verstehe und entwickle.", steps: ["Marketing", "Verkauf", "Digitale Produkte", "Bezahlte Werbung", "Automation", "CRM", "APIs", "Entwicklung", "Datenbanken", "Künstliche Intelligenz", "Vollständige Produkte"] },
    contactSection: { eyebrow: "Kontakt", title: "Bauen wir etwas, das es verdient zu existieren.", text: "Ich bin offen für Chancen in Produktentwicklung, Software, Automation und KI, bei denen der Geschäftskontext genauso zählt wie die technische Umsetzung.", email: "E-Mail", whatsapp: "WhatsApp", sendWhatsapp: "Nachricht auf WhatsApp", sendEmail: "E-Mail senden", signature: "— Bruno", footer: "Mit Neugier von Anfang bis Ende gebaut." },
    misc: { scroll: "scrollen", age: "Jahre alt", discovery: "Entdecken" }
  }
};

const serviceIcons = ["mouse", "screen", "pipeline", "workflow", "bot", "database"];

const experienceByLocale = {
  en: { eyebrow: "Experience", title: "Responsibility over job titles.", intro: "My current work sits where technology, sales operations and product development meet.", current: "Current technology work", currentText: "I contribute to CRM evolution, new features, AI agents, inbound and outbound flows, qualification, prospecting, APIs, webhooks, Meta and WhatsApp integrations, technical troubleshooting and team training.", earlier: "Earlier industrial experience", earlierText: "At FRISAJO AGRO PECUARIA INDUSTRIAL S.A., I worked across administration and production with traceability, system records, weighing, documentation, operational support and training. It taught me discipline and responsibility.", contribution: "I work with owners and teams. I describe my contribution precisely—not as work completed alone." },
  fr: { eyebrow: "Expérience", title: "Les responsabilités avant les titres.", intro: "Mon travail actuel se situe au croisement de la technologie, des opérations de vente et du développement de produits.", current: "Travail actuel en technologie", currentText: "Je contribue à l’évolution de CRM, aux nouvelles fonctions, agents d’IA, flux entrants et sortants, qualification, prospection, API, webhooks, intégrations Meta et WhatsApp, dépannage et formation.", earlier: "Expérience industrielle antérieure", earlierText: "Chez FRISAJO AGRO PECUARIA INDUSTRIAL S.A., j’ai travaillé en administration et en production avec la traçabilité, les registres système, la pesée, les documents, le soutien opérationnel et la formation.", contribution: "Je travaille avec les propriétaires et les équipes. Je décris précisément ma contribution, jamais comme un travail réalisé seul." },
  pt: { eyebrow: "Experiência", title: "Responsabilidades acima de cargos.", intro: "Meu trabalho atual acontece na interseção entre tecnologia, operações comerciais e desenvolvimento de produto.", current: "Atuação atual em tecnologia", currentText: "Contribuo para evolução de CRM, novas funcionalidades, agentes de IA, fluxos inbound e outbound, qualificação, prospecção, APIs, webhooks, integrações Meta e WhatsApp, troubleshooting e treinamento.", earlier: "Experiência industrial anterior", earlierText: "Na FRISAJO AGRO PECUARIA INDUSTRIAL S.A., atuei na administração e produção com rastreabilidade, registros em sistema, pesagem, documentos, suporte operacional e treinamento. Foi uma base de disciplina e responsabilidade.", contribution: "Trabalho junto a donos e equipes. Descrevo minha contribuição com precisão, nunca como algo realizado sozinho." },
  it: { eyebrow: "Esperienza", title: "Le responsabilità prima dei titoli.", intro: "Il mio lavoro attuale unisce tecnologia, operazioni commerciali e sviluppo di prodotto.", current: "Lavoro attuale nella tecnologia", currentText: "Contribuisco all’evoluzione del CRM, nuove funzioni, agenti IA, flussi inbound e outbound, qualificazione, prospecting, API, webhook, integrazioni Meta e WhatsApp, supporto tecnico e formazione.", earlier: "Esperienza industriale precedente", earlierText: "In FRISAJO AGRO PECUARIA INDUSTRIAL S.A. ho lavorato in amministrazione e produzione con tracciabilità, registri, pesatura, documenti, supporto operativo e formazione.", contribution: "Lavoro con proprietari e team. Descrivo con precisione il mio contributo, mai come lavoro svolto da solo." },
  de: { eyebrow: "Erfahrung", title: "Verantwortung vor Jobtiteln.", intro: "Meine heutige Arbeit verbindet Technologie, Verkaufsprozesse und Produktentwicklung.", current: "Aktuelle Arbeit in der Technologie", currentText: "Ich wirke an CRM-Weiterentwicklung, neuen Funktionen, KI-Agenten, Inbound- und Outbound-Abläufen, Qualifizierung, Prospecting, APIs, Webhooks, Meta- und WhatsApp-Integrationen, Fehlerbehebung und Schulung mit.", earlier: "Frühere Industrieerfahrung", earlierText: "Bei FRISAJO AGRO PECUARIA INDUSTRIAL S.A. arbeitete ich in Administration und Produktion mit Rückverfolgbarkeit, Systemeinträgen, Wägung, Dokumentation, operativer Unterstützung und Schulung.", contribution: "Ich arbeite mit Eigentümern und Teams. Meinen Beitrag beschreibe ich präzise, nie als allein erbrachte Arbeit." }
};

const personalByLocale = {
  en: { eyebrow: "Outside the code", title: "Bruno, outside the code.", text: "I was born in Navegantes, Santa Catarina, Brazil. I’m married, have no children and live a quiet life. I prefer family, fishing, animals, nature, technology and useful projects over noise or attention.", quote: "I care more about building something useful than being the person receiving the credit.", values: ["Honesty", "Respect", "Trust", "Simplicity", "Responsibility", "Stability", "Family"], photo: "Photo coming soon" },
  fr: { eyebrow: "Hors du code", title: "Bruno, hors du code.", text: "Je suis né à Navegantes, Santa Catarina, au Brésil. Je suis marié, sans enfants, et je mène une vie tranquille. Je préfère la famille, la pêche, les animaux, la nature, la technologie et les projets utiles au bruit ou à l’attention.", quote: "Je préfère bâtir quelque chose d’utile plutôt que d’être celui qui reçoit le mérite.", values: ["Honnêteté", "Respect", "Confiance", "Simplicité", "Responsabilité", "Stabilité", "Famille"], photo: "Photo à venir" },
  pt: { eyebrow: "Fora do código", title: "Bruno, fora do código.", text: "Nasci em Navegantes, Santa Catarina. Sou casado, não tenho filhos e levo uma vida tranquila. Prefiro família, pesca, animais, natureza, tecnologia e projetos úteis a barulho ou atenção.", quote: "Eu me importo mais em construir algo útil do que em ser a pessoa que recebe o crédito.", values: ["Honestidade", "Respeito", "Confiança", "Simplicidade", "Responsabilidade", "Estabilidade", "Família"], photo: "Foto em breve" },
  it: { eyebrow: "Fuori dal codice", title: "Bruno, fuori dal codice.", text: "Sono nato a Navegantes, Santa Catarina, Brasile. Sono sposato, non ho figli e conduco una vita tranquilla. Preferisco la famiglia, la pesca, gli animali, la natura, la tecnologia e i progetti utili al rumore o all’attenzione.", quote: "Mi interessa più costruire qualcosa di utile che essere la persona che riceve il merito.", values: ["Onestà", "Rispetto", "Fiducia", "Semplicità", "Responsabilità", "Stabilità", "Famiglia"], photo: "Foto in arrivo" },
  de: { eyebrow: "Ausserhalb des Codes", title: "Bruno, ausserhalb des Codes.", text: "Ich wurde in Navegantes im brasilianischen Bundesstaat Santa Catarina geboren, bin verheiratet und habe keine Kinder. Ich lebe ruhig und mag Familie, Angeln, Tiere, Natur, Technologie und sinnvolle Projekte lieber als Lärm oder Aufmerksamkeit.", quote: "Mir ist wichtiger, etwas Nützliches zu bauen, als dafür im Mittelpunkt zu stehen.", values: ["Ehrlichkeit", "Respekt", "Vertrauen", "Einfachheit", "Verantwortung", "Stabilität", "Familie"], photo: "Foto folgt" }
};

export function getCoreContent(locale = "en") {
  const t = dictionaries[locale] ?? dictionaries.en;
  const hrefs = ["#about", "#work", "#experience", "#learning", "#technologies", "#contact"];
  return {
    locale,
    header: { contact: t.contact, navLinks: t.nav.map((label, i) => ({ label, href: hrefs[i] })), aria: { home: "Bruno Steiger", primary: "Primary navigation", mobile: "Mobile navigation", open: "Open navigation", close: "Close navigation", language: t.selectLanguage } },
    hero: { name: "Bruno Steiger", ...t.hero, scroll: t.misc.scroll, blueprintLabels: [t.services.items[0][0], t.services.items[3][0], t.services.items[5][0]], badges: ["__age__", ...t.hero.badges], actions: [{ label: t.hero.work, href: "#work", variant: "primary" }, { label: t.hero.about, href: "#about", variant: "secondary" }] },
    about: { ...t.about, highlights: ["__age__", ...t.about.highlights], ageSuffix: t.hero.ageSuffix },
    services: { eyebrow: t.services.eyebrow, title: t.services.title, subtitle: t.services.subtitle, items: t.services.items.map(([title, description], i) => ({ title, description, icon: serviceIcons[i], discovery: t.misc.discovery })), stats: t.services.stats },
    technologies: { eyebrow: t.technology.eyebrow, title: t.technology.title, subtitle: t.technology.subtitle, toolsLabel: t.technology.toolsLabel, full: t.technology.full, usedIn: { en: "Used in", fr: "Utilisé dans", pt: "Usado em", it: "Utilizzato in", de: "Eingesetzt in" }[locale] ?? "Used in", contextFallback: { en: "Applied across product and operational work", fr: "Appliqué aux produits et aux opérations", pt: "Aplicado em produtos e operações", it: "Applicato a prodotti e operazioni", de: "In Produkt- und Betriebsarbeit eingesetzt" }[locale] ?? "Applied across product and operational work", groups: t.technology.groups.map((title, i) => ({ title, tools: Object.values(tech)[i] })) },
    learning: t.learning,
    experience: experienceByLocale[locale] ?? experienceByLocale.en,
    personal: personalByLocale[locale] ?? personalByLocale.en,
    contact: { ...t.contactSection, details: [{ key: "email", label: t.contactSection.email, value: contactDetails.email }, { key: "whatsapp", label: t.contactSection.whatsapp, value: contactDetails.whatsapp }], actions: [{ label: t.contactSection.sendWhatsapp, href: "https://wa.me/5547992683132", type: "whatsapp", external: true }, { label: t.contactSection.sendEmail, href: `mailto:${contactDetails.email}`, type: "email" }] },
    misc: t.misc
  };
}
